universe   = vanilla
executable = scheduler.sh 
log        = scheduler.log
output     = scheduler.out
error      = scheduler.error
transfer_input_files = start_scheduler.py, scheduler.sh, /root/.ca.crt, /root/.token, job_submit.sh
environment = JHUB_TOKEN={{ token }};JHUB_USER={{ name }};SCHED_PORT={{ sched_port }};DASH_PORT={{ dash_port }},REFRESH_TOKEN={{ refresh_token }},IAM_SERVER={{ iam_server }},IAM_CLIENT_ID={{ client_id }},IAM_CLIENT_SECRET={{ client_secret }}
+OWNER = "condor"
queue
